export type Certainty = 'high' | 'medium' | 'speculative';
export type EventCategory =
  | 'miracle'
  | 'journey'
  | 'discourse'
  | 'council'
  | 'martyrdom'
  | 'vision'
  | 'founding'
  | 'conversion'
  | 'arrest'
  | 'shipwreck';

export interface Location {
  id: string;
  name: string;
  modernName: string;
  lat: number;
  lon: number;
  region: string;
  description: string;
}

export interface Person {
  id: string;
  name: string;
  role: string;
  description: string;
  aliases?: string[];
  died?: string;
  nationality?: string;
}

export interface Source {
  type: 'scripture' | 'extrabiblical';
  reference: string;
  text?: string;
  author?: string;
  work?: string;
  date?: string;
  certainty?: Certainty;
}

export interface BibleEvent {
  id: string;
  title: string;
  description: string;
  dateDisplay: string;
  dateStart: number;
  dateEnd: number;
  certainty: Certainty;
  locationId: string;
  personIds: string[];
  sources: Source[];
  relatedEventIds: string[];
  passage: string;
  book: string;
  category: EventCategory;
  journeyPhase?: string;
}

export const LOCATIONS: Record<string, Location> = {
  jerusalem: {
    id: 'jerusalem',
    name: 'Jerusalem',
    modernName: 'Jerusalem, Israel',
    lat: 31.78,
    lon: 35.22,
    region: 'Judaea',
    description: 'The holy city, seat of the Temple and the Jewish Sanhedrin. Center of the early church.',
  },
  damascus: {
    id: 'damascus',
    name: 'Damascus',
    modernName: 'Damascus, Syria',
    lat: 33.51,
    lon: 36.29,
    region: 'Syria',
    description: 'Ancient city of Syria, first target of Paul\'s persecution mission before his conversion.',
  },
  antioch_syria: {
    id: 'antioch_syria',
    name: 'Antioch (Syria)',
    modernName: 'Antakya, Turkey',
    lat: 36.21,
    lon: 36.16,
    region: 'Syria',
    description: 'Third-largest city of the Roman Empire. Believers were first called "Christians" here. Base of Paul\'s missionary journeys.',
  },
  caesarea: {
    id: 'caesarea',
    name: 'Caesarea Maritima',
    modernName: 'Caesarea, Israel',
    lat: 32.5,
    lon: 34.9,
    region: 'Judaea',
    description: 'Roman administrative capital of Judaea. Built by Herod the Great. Port city on the Mediterranean.',
  },
  joppa: {
    id: 'joppa',
    name: 'Joppa',
    modernName: 'Jaffa / Tel Aviv-Yafo, Israel',
    lat: 32.05,
    lon: 34.75,
    region: 'Judaea',
    description: 'Ancient coastal port city. Where Peter stayed with Simon the tanner and received his vision.',
  },
  lydda: {
    id: 'lydda',
    name: 'Lydda',
    modernName: 'Lod, Israel',
    lat: 31.95,
    lon: 34.89,
    region: 'Judaea',
    description: 'Town in the plain of Sharon, where Peter healed Aeneas.',
  },
  samaria: {
    id: 'samaria',
    name: 'Samaria',
    modernName: 'West Bank, Palestinian Territories',
    lat: 32.27,
    lon: 35.2,
    region: 'Samaria',
    description: 'Region between Judaea and Galilee. Philip the Evangelist preached here and performed signs.',
  },
  paphos: {
    id: 'paphos',
    name: 'Paphos (Cyprus)',
    modernName: 'Paphos, Cyprus',
    lat: 34.77,
    lon: 32.42,
    region: 'Cyprus',
    description: 'Western capital of Cyprus. Site of Elymas the sorcerer\'s blinding and the conversion of the proconsul Sergius Paulus.',
  },
  salamis: {
    id: 'salamis',
    name: 'Salamis (Cyprus)',
    modernName: 'Famagusta District, Cyprus',
    lat: 35.18,
    lon: 33.9,
    region: 'Cyprus',
    description: 'Eastern port city of Cyprus. Paul, Barnabas, and John Mark preached in the synagogues here.',
  },
  pisidian_antioch: {
    id: 'pisidian_antioch',
    name: 'Pisidian Antioch',
    modernName: 'Yalvaç, Turkey',
    lat: 38.3,
    lon: 31.15,
    region: 'Galatia (Pisidia)',
    description: 'Roman colony in the highlands of Pisidia. Paul delivered a landmark synagogue address here.',
  },
  iconium: {
    id: 'iconium',
    name: 'Iconium',
    modernName: 'Konya, Turkey',
    lat: 37.87,
    lon: 32.49,
    region: 'Galatia',
    description: 'Prosperous city of Galatia where Paul and Barnabas preached until expelled.',
  },
  lystra: {
    id: 'lystra',
    name: 'Lystra',
    modernName: 'Hatunsaray / Konya Province, Turkey',
    lat: 37.58,
    lon: 32.45,
    region: 'Galatia',
    description: 'Roman colony in Galatia. Timothy\'s hometown. Paul was stoned here and left for dead.',
  },
  derbe: {
    id: 'derbe',
    name: 'Derbe',
    modernName: 'Kerti Höyük, Turkey',
    lat: 37.35,
    lon: 33.38,
    region: 'Galatia',
    description: 'Eastern city of Galatia. Paul and Barnabas made many disciples here before retracing their steps.',
  },
  tarsus: {
    id: 'tarsus',
    name: 'Tarsus',
    modernName: 'Tarsus, Turkey',
    lat: 36.92,
    lon: 34.89,
    region: 'Cilicia',
    description: 'Paul\'s hometown, a prosperous university city in Cilicia and capital of the province.',
  },
  troas: {
    id: 'troas',
    name: 'Troas',
    modernName: 'Dalyan / Çanakkale Province, Turkey',
    lat: 39.78,
    lon: 26.17,
    region: 'Asia (Mysia)',
    description: 'Port city near the Dardanelles. Paul received the Macedonian vision here and later raised Eutychus.',
  },
  philippi: {
    id: 'philippi',
    name: 'Philippi',
    modernName: 'Near Kavala, Greece',
    lat: 41.01,
    lon: 24.29,
    region: 'Macedonia',
    description: 'Roman colony and leading city of Macedonia. Site of Lydia\'s conversion and Paul\'s imprisonment.',
  },
  thessalonica: {
    id: 'thessalonica',
    name: 'Thessalonica',
    modernName: 'Thessaloniki, Greece',
    lat: 40.64,
    lon: 22.94,
    region: 'Macedonia',
    description: 'Capital and largest city of Macedonia. Paul preached here for three Sabbaths before being expelled.',
  },
  berea: {
    id: 'berea',
    name: 'Berea',
    modernName: 'Veria, Greece',
    lat: 40.52,
    lon: 22.21,
    region: 'Macedonia',
    description: 'Macedonian city whose residents were praised as "noble" for examining the scriptures daily.',
  },
  athens: {
    id: 'athens',
    name: 'Athens',
    modernName: 'Athens, Greece',
    lat: 37.97,
    lon: 23.72,
    region: 'Achaia',
    description: 'Intellectual and cultural capital of Greece. Paul addressed the Areopagus court here.',
  },
  corinth: {
    id: 'corinth',
    name: 'Corinth',
    modernName: 'Corinth, Greece',
    lat: 37.91,
    lon: 22.88,
    region: 'Achaia',
    description: 'Wealthy Roman colony and commercial hub. Paul spent eighteen months here founding a church.',
  },
  ephesus: {
    id: 'ephesus',
    name: 'Ephesus',
    modernName: 'Selçuk, Turkey',
    lat: 37.94,
    lon: 27.34,
    region: 'Asia (Lydia)',
    description: 'One of the greatest cities of the ancient world, home to the Temple of Artemis. Paul spent nearly three years here.',
  },
  miletus: {
    id: 'miletus',
    name: 'Miletus',
    modernName: 'Balat, Turkey',
    lat: 37.53,
    lon: 27.28,
    region: 'Asia',
    description: 'Ancient port city south of Ephesus. Paul delivered his farewell address to Ephesian elders here.',
  },
  malta: {
    id: 'malta',
    name: 'Malta (Melita)',
    modernName: 'Malta',
    lat: 35.92,
    lon: 14.51,
    region: 'Mediterranean Islands',
    description: 'Island in the central Mediterranean. Paul and the ship\'s company were shipwrecked here for three months.',
  },
  rome: {
    id: 'rome',
    name: 'Rome',
    modernName: 'Rome, Italy',
    lat: 41.9,
    lon: 12.49,
    region: 'Italia',
    description: 'Capital of the Roman Empire. Paul arrived here as a prisoner and spent two years under house arrest.',
  },
  puteoli: {
    id: 'puteoli',
    name: 'Puteoli',
    modernName: 'Pozzuoli, Italy',
    lat: 40.82,
    lon: 14.12,
    region: 'Campania',
    description: 'Major Italian port city near Naples. Paul landed here and was welcomed by believers for seven days.',
  },
};

export const PEOPLE: Record<string, Person> = {
  paul: {
    id: 'paul',
    name: 'Paul',
    aliases: ['Saul', 'Saul of Tarsus'],
    role: 'Apostle to the Gentiles',
    nationality: 'Jewish (Roman citizen)',
    description: 'Formerly Saul, a Pharisee and persecutor of the church from Tarsus. After a dramatic conversion on the Damascus road he became the most prolific missionary of the first century, founding churches across Asia Minor, Macedonia, and Greece.',
    died: 'c. 64–68 AD (Rome, martyrdom)',
  },
  peter: {
    id: 'peter',
    name: 'Peter',
    aliases: ['Simon Peter', 'Cephas'],
    role: 'Apostle',
    nationality: 'Jewish (Galilean)',
    description: 'Fisherman from Bethsaida, called by Jesus to be a leading apostle. Preached at Pentecost, oversaw the early Jerusalem church, and pioneered Gentile inclusion through Cornelius.',
    died: 'c. 64–68 AD (Rome, martyrdom)',
  },
  james_apostle: {
    id: 'james_apostle',
    name: 'James (son of Zebedee)',
    aliases: ['James the Greater'],
    role: 'Apostle',
    nationality: 'Jewish (Galilean)',
    description: 'One of the Twelve, brother of John. Among the inner circle of Jesus. First apostle martyred, beheaded by Herod Agrippa I.',
    died: 'c. 44 AD (Jerusalem)',
  },
  james_lord: {
    id: 'james_lord',
    name: 'James (brother of Jesus)',
    aliases: ['James the Just'],
    role: 'Leader of the Jerusalem Church',
    nationality: 'Jewish',
    description: 'Half-brother of Jesus, skeptic during Jesus\'s ministry who became a believer after the resurrection. Presided over the Jerusalem Council and was the pillar of the Jerusalem church.',
    died: 'c. 62 AD (Jerusalem, martyrdom)',
  },
  stephen: {
    id: 'stephen',
    name: 'Stephen',
    role: 'Deacon and Proto-Martyr',
    nationality: 'Jewish (Hellenistic)',
    description: 'One of the Seven Deacons appointed to serve the Jerusalem church. Known for signs and wonders, he delivered a sweeping speech before the Sanhedrin and was stoned to death — the first Christian martyr.',
    died: 'c. 33–36 AD (Jerusalem)',
  },
  philip_evangelist: {
    id: 'philip_evangelist',
    name: 'Philip the Evangelist',
    role: 'Deacon and Evangelist',
    nationality: 'Jewish (Hellenistic)',
    description: 'One of the Seven Deacons. Preached in Samaria, performed miracles, encountered Simon Magus, and led the Ethiopian eunuch to faith.',
  },
  barnabas: {
    id: 'barnabas',
    name: 'Barnabas',
    aliases: ['Joseph of Cyprus'],
    role: 'Apostle and Missionary',
    nationality: 'Jewish (Levite, Cypriot)',
    description: 'A Levite from Cyprus who sold property for the Jerusalem church. Introduced Paul to the apostles and partnered with him on the First Missionary Journey. Later parted with Paul over John Mark.',
  },
  silas: {
    id: 'silas',
    name: 'Silas',
    aliases: ['Silvanus'],
    role: 'Prophet and Missionary',
    nationality: 'Jewish (Roman citizen)',
    description: 'A prophet from the Jerusalem church, sent to deliver the council\'s letter to Antioch. Became Paul\'s companion on the Second Missionary Journey, imprisoned with him in Philippi.',
  },
  timothy: {
    id: 'timothy',
    name: 'Timothy',
    role: 'Missionary and Delegate',
    nationality: 'Greco-Jewish (Lystra)',
    description: 'Son of a Jewish mother and Greek father, from Lystra. Circumcised by Paul for missional reasons. Became Paul\'s closest co-worker and delegate to multiple churches.',
  },
  luke: {
    id: 'luke',
    name: 'Luke',
    role: 'Physician and Historian',
    nationality: 'Greek (Antiochene, possibly)',
    description: 'Physician and travelling companion of Paul. Author of the Gospel of Luke and the Acts of the Apostles. Present in the "we" passages of Acts.',
  },
  priscilla: {
    id: 'priscilla',
    name: 'Priscilla',
    aliases: ['Prisca'],
    role: 'Church Leader and Teacher',
    nationality: 'Jewish (Roman)',
    description: 'Wife of Aquila; the couple were tent-makers expelled from Rome under Claudius. Met Paul in Corinth and later instructed Apollos more fully in Ephesus.',
  },
  aquila: {
    id: 'aquila',
    name: 'Aquila',
    role: 'Tent-maker and Church Leader',
    nationality: 'Jewish (Pontus)',
    description: 'Tent-maker from Pontus, husband of Priscilla. Worked alongside Paul in Corinth, hosted a church in their home.',
  },
  cornelius: {
    id: 'cornelius',
    name: 'Cornelius',
    role: 'Roman Centurion',
    nationality: 'Roman (Italian cohort)',
    description: 'A devout, God-fearing centurion of the Italian Cohort in Caesarea. His household\'s baptism marked the first Gentile inclusion into the church.',
  },
  lydia: {
    id: 'lydia',
    name: 'Lydia',
    role: 'Merchant and Church Patron',
    nationality: 'Greek (Thyatiran)',
    description: 'A dealer in purple cloth from Thyatira, God-fearer. First convert in Europe; her household was baptized and she hosted the Philippian church.',
  },
  apollos: {
    id: 'apollos',
    name: 'Apollos',
    role: 'Teacher and Orator',
    nationality: 'Jewish (Alexandrian)',
    description: 'An eloquent and learned Alexandrian Jew, instructed in the way of the Lord but knowing only John\'s baptism. Priscilla and Aquila explained the way of God more accurately to him.',
  },
  agrippa: {
    id: 'agrippa',
    name: 'Herod Agrippa II',
    role: 'Jewish Client King',
    nationality: 'Herodian Jewish',
    description: 'Son of Agrippa I, great-grandson of Herod the Great. Ruled territories in northern Palestine under Roman supervision. Paul made his defense before him in Caesarea.',
  },
  felix: {
    id: 'felix',
    name: 'Antonius Felix',
    role: 'Roman Governor (Procurator)',
    nationality: 'Roman (freedman)',
    description: 'Procurator of Judaea c. 52–60 AD. Kept Paul in custody for two years hoping for a bribe. Replaced by Festus.',
  },
  festus: {
    id: 'festus',
    name: 'Porcius Festus',
    role: 'Roman Governor (Procurator)',
    nationality: 'Roman',
    description: 'Procurator of Judaea c. 60–62 AD. Inherited Paul\'s case and convened the hearing before Agrippa II.',
  },
};

export const EVENTS: BibleEvent[] = [
  {
    id: 'pentecost',
    title: 'The Day of Pentecost',
    description: 'Fifty days after the Passover during which Jesus was crucified, the Holy Spirit descended on approximately 120 disciples gathered in Jerusalem. Peter delivered a public address citing Joel 2 and Psalm 16; about three thousand people were baptized.',
    dateDisplay: 'c. 30 AD',
    dateStart: 30,
    dateEnd: 30,
    certainty: 'high',
    locationId: 'jerusalem',
    personIds: ['peter', 'luke'],
    sources: [
      { type: 'scripture', reference: 'Acts 2:1–41', text: 'When the day of Pentecost came, they were all together in one place.' },
      { type: 'extrabiblical', reference: 'Josephus, Ant. 18.63–64', author: 'Josephus', work: 'Antiquities of the Jews', date: 'c. 93 AD', certainty: 'medium' },
    ],
    relatedEventIds: ['stephen_martyrdom', 'peter_cornelius'],
    passage: 'Acts 2:1–41',
    book: 'Acts',
    category: 'founding',
  },
  {
    id: 'stephen_martyrdom',
    title: 'Martyrdom of Stephen',
    description: 'Stephen, one of the Seven Deacons, was arrested and brought before the Sanhedrin. He delivered a lengthy speech recounting Israel\'s history before accusing his accusers. The council dragged him out of the city and stoned him. Saul of Tarsus consented and guarded the cloaks.',
    dateDisplay: 'c. 33–36 AD',
    dateStart: 33,
    dateEnd: 36,
    certainty: 'medium',
    locationId: 'jerusalem',
    personIds: ['stephen', 'paul'],
    sources: [
      { type: 'scripture', reference: 'Acts 6:8–8:3', text: 'While they were stoning him, Stephen prayed, "Lord Jesus, receive my spirit."' },
    ],
    relatedEventIds: ['paul_conversion', 'philip_samaria'],
    passage: 'Acts 6:8–8:3',
    book: 'Acts',
    category: 'martyrdom',
  },
  {
    id: 'philip_samaria',
    title: 'Philip Preaches in Samaria',
    description: 'Following the persecution after Stephen\'s death, Philip went to a city in Samaria and proclaimed the Messiah. Large crowds paid attention and many with unclean spirits were healed. Simon Magus, a sorcerer of great renown, was baptized.',
    dateDisplay: 'c. 33–36 AD',
    dateStart: 33,
    dateEnd: 36,
    certainty: 'medium',
    locationId: 'samaria',
    personIds: ['philip_evangelist'],
    sources: [
      { type: 'scripture', reference: 'Acts 8:4–25' },
    ],
    relatedEventIds: ['stephen_martyrdom', 'paul_conversion'],
    passage: 'Acts 8:4–25',
    book: 'Acts',
    category: 'founding',
  },
  {
    id: 'paul_conversion',
    title: "Saul's Conversion on the Damascus Road",
    description: "Breathing out murderous threats against the disciples, Saul obtained letters from the high priest authorizing him to arrest believers in Damascus. Near the city, a blinding light from heaven flashed and he heard the voice of Jesus. He arrived in Damascus blind, fasted three days, and was baptized by Ananias.",
    dateDisplay: 'c. 33–36 AD',
    dateStart: 33,
    dateEnd: 36,
    certainty: 'medium',
    locationId: 'damascus',
    personIds: ['paul'],
    sources: [
      { type: 'scripture', reference: 'Acts 9:1–22', text: '"Saul, Saul, why do you persecute me?"' },
      { type: 'scripture', reference: 'Galatians 1:15–17' },
      { type: 'extrabiblical', reference: 'Eusebius, Hist. Eccl. 2.3', author: 'Eusebius', work: 'Historia Ecclesiastica', date: 'c. 313 AD', certainty: 'low' },
    ],
    relatedEventIds: ['stephen_martyrdom', 'paul_first_jerusalem_visit'],
    passage: 'Acts 9:1–22',
    book: 'Acts',
    category: 'conversion',
  },
  {
    id: 'peter_tabitha',
    title: 'Tabitha Raised from the Dead',
    description: 'Peter was summoned to Joppa after Tabitha (Dorcas), a disciple known for charity, died. Peter sent everyone out, knelt and prayed, then said "Tabitha, get up." She opened her eyes and Peter presented her alive.',
    dateDisplay: 'c. 37–40 AD',
    dateStart: 37,
    dateEnd: 40,
    certainty: 'medium',
    locationId: 'joppa',
    personIds: ['peter'],
    sources: [
      { type: 'scripture', reference: 'Acts 9:36–43' },
    ],
    relatedEventIds: ['peter_cornelius', 'peter_aeneas'],
    passage: 'Acts 9:36–43',
    book: 'Acts',
    category: 'miracle',
  },
  {
    id: 'peter_aeneas',
    title: 'Healing of Aeneas at Lydda',
    description: 'In Lydda, Peter found a man named Aeneas who had been bedridden for eight years, paralyzed. Peter said, "Aeneas, Jesus Christ heals you. Get up and roll up your mat." He got up immediately.',
    dateDisplay: 'c. 37–40 AD',
    dateStart: 37,
    dateEnd: 40,
    certainty: 'medium',
    locationId: 'lydda',
    personIds: ['peter'],
    sources: [
      { type: 'scripture', reference: 'Acts 9:32–35' },
    ],
    relatedEventIds: ['peter_tabitha'],
    passage: 'Acts 9:32–35',
    book: 'Acts',
    category: 'miracle',
  },
  {
    id: 'peter_cornelius',
    title: 'Cornelius and the Gentile Pentecost',
    description: "While fasting on a rooftop in Joppa, Peter received a vision of a sheet lowered from heaven containing all kinds of animals, with a voice commanding him to eat. He was then summoned to Caesarea by Cornelius, a Roman centurion who had received an angelic vision. As Peter spoke, the Holy Spirit fell on Cornelius's household — the first documented Gentile conversion.",
    dateDisplay: 'c. 40–42 AD',
    dateStart: 40,
    dateEnd: 42,
    certainty: 'medium',
    locationId: 'caesarea',
    personIds: ['peter', 'cornelius'],
    sources: [
      { type: 'scripture', reference: 'Acts 10:1–11:18', text: 'The Holy Spirit came on all who heard the message.' },
    ],
    relatedEventIds: ['antioch_church', 'jerusalem_council'],
    passage: 'Acts 10:1–11:18',
    book: 'Acts',
    category: 'founding',
  },
  {
    id: 'antioch_church',
    title: 'Church Founded at Antioch of Syria',
    description: 'Believers scattered by the persecution after Stephen made it to Antioch and began speaking to Greeks as well as Jews. Barnabas was sent from Jerusalem to investigate and, recognizing the grace of God, went to Tarsus to find Saul. For a whole year they met with the church. It was in Antioch that disciples were first called Christians.',
    dateDisplay: 'c. 40–43 AD',
    dateStart: 40,
    dateEnd: 43,
    certainty: 'medium',
    locationId: 'antioch_syria',
    personIds: ['barnabas', 'paul'],
    sources: [
      { type: 'scripture', reference: 'Acts 11:19–26', text: 'The disciples were called Christians first at Antioch.' },
    ],
    relatedEventIds: ['first_missionary_journey', 'peter_cornelius'],
    passage: 'Acts 11:19–26',
    book: 'Acts',
    category: 'founding',
  },
  {
    id: 'james_martyrdom',
    title: 'Martyrdom of James the Apostle',
    description: "King Herod Agrippa I had James, the brother of John, put to death with the sword. This pleased the Jewish authorities, so Agrippa also arrested Peter. The date is fixed by Josephus's account of Agrippa I's death at Passover 44 AD.",
    dateDisplay: 'c. 44 AD',
    dateStart: 44,
    dateEnd: 44,
    certainty: 'high',
    locationId: 'jerusalem',
    personIds: ['james_apostle', 'peter'],
    sources: [
      { type: 'scripture', reference: 'Acts 12:1–5' },
      { type: 'extrabiblical', reference: 'Josephus, Ant. 19.343–352', author: 'Josephus', work: 'Antiquities of the Jews', date: 'c. 93 AD', certainty: 'high' },
    ],
    relatedEventIds: ['peter_imprisonment', 'first_missionary_journey'],
    passage: 'Acts 12:1–5',
    book: 'Acts',
    category: 'martyrdom',
  },
  {
    id: 'peter_imprisonment',
    title: "Peter's Miraculous Release from Prison",
    description: "After James's execution, Herod imprisoned Peter, intending to bring him to trial after Passover. The night before his trial, an angel appeared, woke Peter, and led him past two guards out through the iron city gate, which opened by itself. Peter went to the house of Mary, mother of John Mark, where believers were praying.",
    dateDisplay: 'c. 44 AD',
    dateStart: 44,
    dateEnd: 44,
    certainty: 'high',
    locationId: 'jerusalem',
    personIds: ['peter'],
    sources: [
      { type: 'scripture', reference: 'Acts 12:6–19' },
    ],
    relatedEventIds: ['james_martyrdom'],
    passage: 'Acts 12:6–19',
    book: 'Acts',
    category: 'miracle',
  },
  {
    id: 'first_missionary_journey',
    title: 'First Missionary Journey — Cyprus',
    description: 'Set apart by the Holy Spirit and commissioned by the church in Antioch, Barnabas and Saul sailed to Cyprus. In Paphos they encountered Elymas the sorcerer, who opposed them before the proconsul Sergius Paulus. Paul, filled with the Spirit, struck Elymas blind. Sergius Paulus believed.',
    dateDisplay: 'c. 46–47 AD',
    dateStart: 46,
    dateEnd: 47,
    certainty: 'medium',
    locationId: 'paphos',
    personIds: ['paul', 'barnabas'],
    sources: [
      { type: 'scripture', reference: 'Acts 13:1–12' },
    ],
    relatedEventIds: ['first_journey_galatia', 'jerusalem_council'],
    passage: 'Acts 13:1–12',
    book: 'Acts',
    category: 'journey',
    journeyPhase: 'First Missionary Journey',
  },
  {
    id: 'first_journey_galatia',
    title: 'First Missionary Journey — Galatia',
    description: 'From Cyprus, Paul and Barnabas traveled to the mainland cities of Pisidian Antioch, Iconium, Lystra, and Derbe. At Lystra, Paul healed a man lame from birth, and the crowd hailed them as Hermes and Zeus. Paul was subsequently stoned by Jews from Antioch and Iconium and left for dead outside the city.',
    dateDisplay: 'c. 47–48 AD',
    dateStart: 47,
    dateEnd: 48,
    certainty: 'medium',
    locationId: 'lystra',
    personIds: ['paul', 'barnabas', 'timothy'],
    sources: [
      { type: 'scripture', reference: 'Acts 13:13–14:28' },
      { type: 'scripture', reference: 'Galatians 4:13–15' },
    ],
    relatedEventIds: ['first_missionary_journey', 'jerusalem_council'],
    passage: 'Acts 13:13–14:28',
    book: 'Acts',
    category: 'journey',
    journeyPhase: 'First Missionary Journey',
  },
  {
    id: 'jerusalem_council',
    title: 'Jerusalem Council',
    description: 'A controversy arose in Antioch over whether Gentile converts must be circumcised according to the Law of Moses. Paul, Barnabas, and others were sent to Jerusalem to settle the question. After debate, James proposed a compromise letter affirming that Gentiles need not be circumcised, citing Amos 9:11–12.',
    dateDisplay: 'c. 49 AD',
    dateStart: 49,
    dateEnd: 49,
    certainty: 'high',
    locationId: 'jerusalem',
    personIds: ['paul', 'barnabas', 'peter', 'james_lord'],
    sources: [
      { type: 'scripture', reference: 'Acts 15:1–35' },
      { type: 'scripture', reference: 'Galatians 2:1–10' },
    ],
    relatedEventIds: ['first_journey_galatia', 'second_missionary_journey'],
    passage: 'Acts 15:1–35',
    book: 'Acts',
    category: 'council',
  },
  {
    id: 'second_missionary_journey',
    title: 'Second Missionary Journey — Macedonian Vision',
    description: 'Paul and Silas traveled overland through Syria, Cilicia, and the Galatian churches, adding Timothy at Lystra. Prevented by the Spirit from entering Bithynia, they came to Troas where Paul saw a vision in the night: a Macedonian man saying "Come over to Macedonia and help us."',
    dateDisplay: 'c. 49–50 AD',
    dateStart: 49,
    dateEnd: 50,
    certainty: 'medium',
    locationId: 'troas',
    personIds: ['paul', 'silas', 'timothy', 'luke'],
    sources: [
      { type: 'scripture', reference: 'Acts 15:36–16:10' },
    ],
    relatedEventIds: ['lydia_conversion', 'paul_philippi_prison'],
    passage: 'Acts 15:36–16:10',
    book: 'Acts',
    category: 'vision',
    journeyPhase: 'Second Missionary Journey',
  },
  {
    id: 'lydia_conversion',
    title: "Lydia's Conversion — First European Convert",
    description: 'At Philippi, on the Sabbath, Paul and companions went to a place of prayer by the river and spoke to women gathered there. Lydia, a dealer in purple cloth from Thyatira, listened and the Lord opened her heart. She and her household were baptized and she urged the missionaries to stay in her home.',
    dateDisplay: 'c. 50 AD',
    dateStart: 50,
    dateEnd: 50,
    certainty: 'medium',
    locationId: 'philippi',
    personIds: ['paul', 'silas', 'luke', 'lydia'],
    sources: [
      { type: 'scripture', reference: 'Acts 16:11–15', text: 'The Lord opened her heart to respond to Paul\'s message.' },
    ],
    relatedEventIds: ['paul_philippi_prison', 'second_missionary_journey'],
    passage: 'Acts 16:11–15',
    book: 'Acts',
    category: 'conversion',
    journeyPhase: 'Second Missionary Journey',
  },
  {
    id: 'paul_philippi_prison',
    title: 'Paul and Silas Imprisoned at Philippi',
    description: 'After exorcising a slave girl of a divining spirit, her owners dragged Paul and Silas before the magistrates. They were flogged and thrown into the inner cell of the prison with feet in stocks. At midnight they prayed and sang hymns. An earthquake opened every door and loosed every chain. The jailer, on the verge of suicide, was saved.',
    dateDisplay: 'c. 50 AD',
    dateStart: 50,
    dateEnd: 50,
    certainty: 'medium',
    locationId: 'philippi',
    personIds: ['paul', 'silas'],
    sources: [
      { type: 'scripture', reference: 'Acts 16:16–40' },
    ],
    relatedEventIds: ['lydia_conversion', 'paul_thessalonica'],
    passage: 'Acts 16:16–40',
    book: 'Acts',
    category: 'miracle',
    journeyPhase: 'Second Missionary Journey',
  },
  {
    id: 'paul_thessalonica',
    title: 'Paul in Thessalonica',
    description: 'Paul reasoned in the Thessalonian synagogue for three Sabbaths, arguing from Scripture that the Messiah had to suffer and rise. Some Jews and a large number of God-fearing Greeks were persuaded. Opponents incited a mob, forcing Paul and Silas to leave by night for Berea.',
    dateDisplay: 'c. 50–51 AD',
    dateStart: 50,
    dateEnd: 51,
    certainty: 'medium',
    locationId: 'thessalonica',
    personIds: ['paul', 'silas', 'timothy'],
    sources: [
      { type: 'scripture', reference: 'Acts 17:1–9' },
      { type: 'scripture', reference: '1 Thessalonians 2:1–12' },
    ],
    relatedEventIds: ['paul_philippi_prison', 'paul_athens'],
    passage: 'Acts 17:1–9',
    book: 'Acts',
    category: 'discourse',
    journeyPhase: 'Second Missionary Journey',
  },
  {
    id: 'paul_athens',
    title: 'Paul at the Areopagus, Athens',
    description: 'Waiting for Silas and Timothy in Athens, Paul was provoked by the city full of idols and debated in the synagogue and the agora. Invited to the Areopagus, he delivered his famous address beginning, "Men of Athens, I see that in every way you are very religious," citing the altar "To an Unknown God" and Aratus\'s poem Phaenomena.',
    dateDisplay: 'c. 51 AD',
    dateStart: 51,
    dateEnd: 51,
    certainty: 'medium',
    locationId: 'athens',
    personIds: ['paul'],
    sources: [
      { type: 'scripture', reference: 'Acts 17:16–34', text: '"In him we live and move and have our being." — Acts 17:28, citing Aratus, Phaenomena 5' },
      { type: 'extrabiblical', reference: 'Aratus, Phaenomena, line 5', author: 'Aratus of Soli', work: 'Phaenomena', date: 'c. 275 BC', certainty: 'high' },
    ],
    relatedEventIds: ['paul_thessalonica', 'paul_corinth'],
    passage: 'Acts 17:16–34',
    book: 'Acts',
    category: 'discourse',
    journeyPhase: 'Second Missionary Journey',
  },
  {
    id: 'paul_corinth',
    title: 'Paul in Corinth — Eighteen Months',
    description: 'Paul arrived in Corinth and met Aquila and Priscilla, recently expelled from Rome under Claudius\'s edict. He worked as a tent-maker with them. When Silas and Timothy arrived from Macedonia he devoted himself entirely to preaching. He appeared before the proconsul Gallio, whose accession is independently dated to 51–52 AD — one of the firmest anchors in Pauline chronology.',
    dateDisplay: 'c. 51–52 AD',
    dateStart: 51,
    dateEnd: 52,
    certainty: 'high',
    locationId: 'corinth',
    personIds: ['paul', 'priscilla', 'aquila', 'silas', 'timothy'],
    sources: [
      { type: 'scripture', reference: 'Acts 18:1–18' },
      { type: 'extrabiblical', reference: 'Claudius Edict (Suetonius, Claud. 25.4)', author: 'Suetonius', work: 'De Vita Caesarum', date: 'c. 121 AD', certainty: 'high' },
      { type: 'extrabiblical', reference: 'Delphi Inscription (Gallio Inscription)', work: 'SIG³ 801D', date: 'c. 52 AD', certainty: 'high' },
    ],
    relatedEventIds: ['paul_athens', 'third_missionary_journey_ephesus'],
    passage: 'Acts 18:1–18',
    book: 'Acts',
    category: 'founding',
    journeyPhase: 'Second Missionary Journey',
  },
  {
    id: 'third_missionary_journey_ephesus',
    title: 'Third Missionary Journey — Two Years at Ephesus',
    description: 'Paul entered the synagogue and reasoned for three months. After opposition he withdrew to the lecture hall of Tyrannus, arguing daily for two years, so that all who lived in Asia heard the word of the Lord. Extraordinary miracles occurred; handkerchiefs that had touched Paul were carried to the sick. Silversmiths\' guild led by Demetrius incited a riot over the shrine trade.',
    dateDisplay: 'c. 52–55 AD',
    dateStart: 52,
    dateEnd: 55,
    certainty: 'medium',
    locationId: 'ephesus',
    personIds: ['paul', 'priscilla', 'aquila', 'timothy', 'apollos'],
    sources: [
      { type: 'scripture', reference: 'Acts 18:23–19:41' },
      { type: 'extrabiblical', reference: 'Pliny the Elder, Nat. Hist. 5.31', author: 'Pliny the Elder', work: 'Naturalis Historia', date: 'c. 77 AD', certainty: 'medium' },
    ],
    relatedEventIds: ['paul_corinth', 'paul_miletus_farewell', 'paul_arrest_jerusalem'],
    passage: 'Acts 18:23–19:41',
    book: 'Acts',
    category: 'founding',
    journeyPhase: 'Third Missionary Journey',
  },
  {
    id: 'eutychus_raised',
    title: 'Eutychus Raised at Troas',
    description: 'In Troas, Paul spoke late into the night in an upstairs room lit with many lamps. A young man named Eutychus, seated in a window, fell asleep and plunged three floors to his death. Paul went down, threw himself on the young man, and declared "his life is in him." He was taken home alive.',
    dateDisplay: 'c. 57 AD',
    dateStart: 57,
    dateEnd: 57,
    certainty: 'medium',
    locationId: 'troas',
    personIds: ['paul', 'luke'],
    sources: [
      { type: 'scripture', reference: 'Acts 20:7–12' },
    ],
    relatedEventIds: ['paul_miletus_farewell'],
    passage: 'Acts 20:7–12',
    book: 'Acts',
    category: 'miracle',
    journeyPhase: 'Third Missionary Journey',
  },
  {
    id: 'paul_miletus_farewell',
    title: "Paul's Farewell Address to the Ephesian Elders",
    description: 'Having bypassed Ephesus to avoid delay, Paul summoned the elders of the church to Miletus. He reviewed his ministry among them and warned of coming hardship, declaring, "I know that none of you among whom I have gone about preaching the kingdom will ever see me again." He knelt on the beach and prayed with them all.',
    dateDisplay: 'c. 57 AD',
    dateStart: 57,
    dateEnd: 57,
    certainty: 'medium',
    locationId: 'miletus',
    personIds: ['paul', 'luke'],
    sources: [
      { type: 'scripture', reference: 'Acts 20:17–38', text: '"Keep watch over yourselves and all the flock of which the Holy Spirit has made you overseers."' },
    ],
    relatedEventIds: ['eutychus_raised', 'paul_arrest_jerusalem'],
    passage: 'Acts 20:17–38',
    book: 'Acts',
    category: 'discourse',
    journeyPhase: 'Third Missionary Journey',
  },
  {
    id: 'paul_arrest_jerusalem',
    title: "Paul's Arrest in Jerusalem",
    description: 'Paul entered the Temple to complete a purification rite when Jews from Asia incited a crowd, claiming he had brought Greeks past the barrier into the inner courts. A riot erupted and the Roman tribune Claudius Lysias intervened. Paul addressed the crowd in Aramaic from the barracks steps, speaking of his conversion, before being removed by force.',
    dateDisplay: 'c. 57 AD',
    dateStart: 57,
    dateEnd: 57,
    certainty: 'medium',
    locationId: 'jerusalem',
    personIds: ['paul'],
    sources: [
      { type: 'scripture', reference: 'Acts 21:27–22:30' },
    ],
    relatedEventIds: ['paul_miletus_farewell', 'paul_caesarea_felix'],
    passage: 'Acts 21:27–22:30',
    book: 'Acts',
    category: 'arrest',
  },
  {
    id: 'paul_caesarea_felix',
    title: "Paul Before Felix in Caesarea",
    description: "Transferred by night to Caesarea under heavy guard, Paul appeared before the governor Felix. The high priest Ananias and a lawyer Tertullus prosecuted him. Felix adjourned the case and kept Paul in custody for two years, frequently sending for him to converse — reportedly hoping for a bribe.",
    dateDisplay: 'c. 57–59 AD',
    dateStart: 57,
    dateEnd: 59,
    certainty: 'medium',
    locationId: 'caesarea',
    personIds: ['paul', 'felix'],
    sources: [
      { type: 'scripture', reference: 'Acts 23:23–24:27' },
      { type: 'extrabiblical', reference: 'Tacitus, Ann. 12.54', author: 'Tacitus', work: 'Annales', date: 'c. 117 AD', certainty: 'medium' },
    ],
    relatedEventIds: ['paul_arrest_jerusalem', 'paul_festus_agrippa'],
    passage: 'Acts 23:23–24:27',
    book: 'Acts',
    category: 'arrest',
  },
  {
    id: 'paul_festus_agrippa',
    title: "Paul Before Festus and Agrippa II",
    description: 'When Festus succeeded Felix, the chief priests renewed their case against Paul. Paul appealed to Caesar, triggering his transfer to Rome. King Agrippa II and Bernice arrived in Caesarea; Festus presented Paul\'s case. Paul delivered his defense, describing his conversion and mission. Agrippa remarked, "Do you think that in such a short time you can persuade me to be a Christian?"',
    dateDisplay: 'c. 59 AD',
    dateStart: 59,
    dateEnd: 59,
    certainty: 'medium',
    locationId: 'caesarea',
    personIds: ['paul', 'festus', 'agrippa'],
    sources: [
      { type: 'scripture', reference: 'Acts 25:1–26:32' },
    ],
    relatedEventIds: ['paul_caesarea_felix', 'paul_shipwreck_malta'],
    passage: 'Acts 25:1–26:32',
    book: 'Acts',
    category: 'discourse',
  },
  {
    id: 'paul_shipwreck_malta',
    title: 'Shipwreck at Malta',
    description: 'Sailing westward in late autumn under adverse conditions, the ship was caught in a violent northeaster (Euraquilo). After fourteen days adrift in the Adriatic, near soundings indicating land, the sailors attempted to escape in the lifeboat. Paul, who had warned against sailing, now declared that all 276 aboard would be saved. The ship ran aground and broke up. All reached shore safely.',
    dateDisplay: 'c. 59–60 AD',
    dateStart: 59,
    dateEnd: 60,
    certainty: 'high',
    locationId: 'malta',
    personIds: ['paul', 'luke'],
    sources: [
      { type: 'scripture', reference: 'Acts 27:1–28:10', text: '"Not one of you will lose a single hair from his head." — Acts 27:34' },
    ],
    relatedEventIds: ['paul_festus_agrippa', 'paul_rome'],
    passage: 'Acts 27:1–28:10',
    book: 'Acts',
    category: 'shipwreck',
  },
  {
    id: 'paul_rome',
    title: "Paul's Arrival and House Arrest in Rome",
    description: 'Paul arrived in Rome and was allowed to live by himself with a soldier as guard. He met first with the Jewish leaders, explaining his situation and debating from Moses and the Prophets about the kingdom of God and Jesus. For two full years he welcomed all who came to him, preaching the kingdom of God and teaching about the Lord Jesus Christ openly and unhindered.',
    dateDisplay: 'c. 60–62 AD',
    dateStart: 60,
    dateEnd: 62,
    certainty: 'high',
    locationId: 'rome',
    personIds: ['paul', 'luke'],
    sources: [
      { type: 'scripture', reference: 'Acts 28:11–31', text: '"He proclaimed the kingdom of God and taught about the Lord Jesus Christ — with all boldness and without hindrance."' },
      { type: 'extrabiblical', reference: 'Eusebius, Hist. Eccl. 2.22', author: 'Eusebius', work: 'Historia Ecclesiastica', date: 'c. 313 AD', certainty: 'medium' },
    ],
    relatedEventIds: ['paul_shipwreck_malta'],
    passage: 'Acts 28:11–31',
    book: 'Acts',
    category: 'founding',
  },
];

export const JOURNEY_ROUTES: Record<string, { locationIds: string[]; color: string; label: string }> = {
  first: {
    label: 'First Missionary Journey (c. 46–48 AD)',
    color: '#c9922a',
    locationIds: ['antioch_syria', 'salamis', 'paphos', 'pisidian_antioch', 'iconium', 'lystra', 'derbe', 'antioch_syria'],
  },
  second: {
    label: 'Second Missionary Journey (c. 49–52 AD)',
    color: '#7a9a8a',
    locationIds: ['antioch_syria', 'tarsus', 'lystra', 'troas', 'philippi', 'thessalonica', 'berea', 'athens', 'corinth', 'ephesus', 'caesarea', 'antioch_syria'],
  },
  third: {
    label: 'Third Missionary Journey (c. 52–57 AD)',
    color: '#7a5a9a',
    locationIds: ['antioch_syria', 'tarsus', 'ephesus', 'troas', 'philippi', 'corinth', 'philippi', 'troas', 'miletus', 'caesarea', 'jerusalem'],
  },
  rome: {
    label: 'Voyage to Rome (c. 59–60 AD)',
    color: '#8a2020',
    locationIds: ['caesarea', 'malta', 'puteoli', 'rome'],
  },
};

export const CATEGORY_COLORS: Record<EventCategory, string> = {
  miracle: '#7a9a8a',
  journey: '#c9922a',
  discourse: '#7a5a9a',
  council: '#5a7a9a',
  martyrdom: '#8a2020',
  vision: '#9a7a3a',
  founding: '#4a8a6a',
  conversion: '#c9922a',
  arrest: '#7a3528',
  shipwreck: '#4a6a8a',
};

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  miracle: 'Miracle',
  journey: 'Journey',
  discourse: 'Discourse',
  council: 'Council',
  martyrdom: 'Martyrdom',
  vision: 'Vision',
  founding: 'Founding',
  conversion: 'Conversion',
  arrest: 'Arrest',
  shipwreck: 'Shipwreck',
};
